services:
  api_portfolio:
    container_name: api_portfolio
    hostname: api_portfolio
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - proxy
    volumes:
      - backend:/usr/src/app/public

volumes:
  backend:
    external: true

networks:
  proxy:
    external: true
